# Project information
site_name: 'Open Source SOC'
site_description: 'Docker Compose files to create an open source Security Operations Center (SOC) for testing and learning.'
site_author: 'Ironstone Labs'
site_url: 'https://ironstone-labs.github.io/OSSIEM/'

# Repository
repo_name: 'OSSIEM'
repo_url: 'https://github.com/Ironstone-Labs/OSSIEM/'

# Copyright
copyright: 'Copyright &copy; 2025-2026 Ironstone Labs<br>This documentation is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'

# Navigation Menu
nav:
  - About: 'index.md'
  - Roadmap: 'roadmap.md'
  - Quick Start: 'quickstart/index.md'
  - SOC Fortress:
    - Overview: 'socfortress/overview.md'
    - CoPilot:
      - Overview: 'socfortress/copilot/overview.md'
      - Installation: 'socfortress/copilot/installation.md'
      - Configuration: 'socfortress/copilot/configuration.md'
      - Usage: 'socfortress/copilot/usage.md'
    - Talon:
      - Overview: 'socfortress/talon/overview.md'
      - Installation: 'socfortress/talon/installation.md'
      - Configuration: 'socfortress/talon/configuration.md'
      - Usage: 'socfortress/talon/usage.md'
  - Cloudflared:
    - Overview: 'cloudflared/overview.md'
    - Installation: 'cloudflared/installation.md'
    - Configuration: 'cloudflared/configuration.md'
    - Usage: 'cloudflared/usage.md'
  - SOAR:
    - Overview: 'soar/overview.md'
    - Shuffle:
      - Overview: 'soar/shuffle/overview.md'
      - Installation: 'soar/shuffle/installation.md'
      - Configuration: 'soar/shuffle/configuration.md'
      - Usage: 'soar/shuffle/usage.md'
    - n8n:
      - Overview: 'soar/n8n/overview.md'
      - Installation: 'soar/n8n/installation.md'
      - Configuration: 'soar/n8n/configuration.md'
      - Usage: 'soar/n8n/usage.md'
  - Threat Intelligence:
    - Overview: 'threatintelligence/overview.md'
    - MISP:
      - Overview: 'threatintelligence/misp/overview.md'
      - Installation: 'threatintelligence/misp/installation.md'
      - Configuration: 'threatintelligence/misp/configuration.md'
      - Usage: 'threatintelligence/misp/usage.md'
    - OpenCTI:
      - Overview: 'threatintelligence/opencti/overview.md'
      - Installation: 'threatintelligence/opencti/installation.md'
      - Configuration: 'threatintelligence/opencti/configuration.md'
      - Usage: 'threatintelligence/opencti/usage.md'
  - CISO Assistant:
    - Overview: 'cisoassistant/overview.md'
    - Installation: 'cisoassistant/installation.md'
    - Configuration: 'cisoassistant/configuration.md'
    - Usage: 'cisoassistant/usage.md'
  - Adversarial Exposure Validation:
    - Overview: 'adversarialexposurevalidation/overview.md'
    - Installation: 'adversarialexposurevalidation/installation.md'
    - Configuration: 'adversarialexposurevalidation/configuration.md'
    - Usage: 'adversarialexposurevalidation/usage.md'
  - AC-Hunter:
    - Overview: 'ac-hunter/overview.md'
    - Installation: 'ac-hunter/installation.md'
    - Configuration: 'ac-hunter/configuration.md'
    - Usage: 'ac-hunter/usage.md'
  - Resources: 'resources.md'

# Configuration
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    admonition:
      cite: octicons/link-external-16
    logo: material/file-document-edit-outline

# Customization
extra:
  social:
    - icon: material/cloud
      link: https://ironstoneinfosec.com
    - icon: fontawesome/brands/github
      link: https://github.com/Ironstone-Labs

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      use_pygments: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true